### ISSUE TITLE
Document HttpRequest's body handler asynchronous behaviour

### ISSUE THREAD

**Issue by franz1981** [Hyperfoil/hyperfoil.github.io#55]
HttpRequest's body handling, with subsequent store of the processed body in a variable, can bite users which expect it to be synchronous with other(s) steps which use its result eg

```yaml
         scenario:
          - login:
            - pullSharedMap:
                key: policyHolder
                vars: [ email, password, vehicles, insured ]
            - httpRequest:
                endpoint: insurance
                GET: whatever
                headers:
                  accept: application/json
                handler:
                  body:
                    json: .token -> token
         - viewUser:
            - httpRequest:
                endpoint: insurance
                GET: wot
                headers:
                  auth: ${token}
                  accept: application/json
```

`${token}` shouldn't assume that `token` is been set!
Indeed to achieve that ordering should add `awaitVar token` in `viewUser`, before `httpRequest` or in `login` after `httpRequest`.
